CREATE TABLE IF NOT EXISTS orders (
  id SERIAL PRIMARY KEY,
  customer VARCHAR(120) NOT NULL,
  sku VARCHAR(40) NOT NULL,
  quantity INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'CREATED'
);
