apiVersion: v1
kind: ConfigMap
metadata:
  name: loja-veloz-config
  namespace: loja-veloz
data:
  APP_VERSION: "1.0.0"
  ORDERS_URL: "http://orders:8001"
  PAYMENTS_URL: "http://payments:8002"
  STOCK_URL: "http://stock:8003"
