version: '3.9'
services:
  api-gateway:
    build: ./services/api-gateway
    image: ghcr.io/exemplo/loja-veloz-api-gateway:1.0.0
    ports:
      - "8000:8000"
    environment:
      APP_VERSION: 1.0.0
      ORDERS_URL: http://orders:8001
      PAYMENTS_URL: http://payments:8002
      STOCK_URL: http://stock:8003
    depends_on:
      - orders
      - payments
      - stock
    networks: [veloz-net]

  orders:
    build: ./services/orders
    image: ghcr.io/exemplo/loja-veloz-orders:1.0.0
    environment:
      APP_VERSION: 1.0.0
      DB_PATH: /data/orders.db
    volumes:
      - orders-data:/data
    networks: [veloz-net]

  payments:
    build: ./services/payments
    image: ghcr.io/exemplo/loja-veloz-payments:1.0.0
    environment:
      APP_VERSION: 1.0.0
    networks: [veloz-net]

  stock:
    build: ./services/stock
    image: ghcr.io/exemplo/loja-veloz-stock:1.0.0
    environment:
      APP_VERSION: 1.0.0
    networks: [veloz-net]

networks:
  veloz-net:
    driver: bridge

volumes:
  orders-data:
